[versions]
androidGradlePlugin = "9.0.0"
android-compileSdk = "36"
android-minSdk = "26"
androidxActivity = "1.12.3"
androidxLintGradle = "1.0.0-alpha05"
composeMultiplatform = "1.10.0"
junit = "4.13.2"
navigationEvent = "1.0.1"
kotlin = "2.3.0"
material3 = "1.10.0-alpha05"
robolectric = "4.16.1"
jetbrainsKotlinJvm = "2.3.0"
vanniktechMavenPublish = "0.36.0"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidx-lint-gradle = { module = "androidx.lint:lint-gradle", version.ref = "androidxLintGradle" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-ui-test-junit4 = { group = "org.jetbrains.compose.ui", name = "ui-test-junit4", version.ref = "composeMultiplatform" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version.ref = "composeMultiplatform" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-navigation-event = { module = "androidx.navigationevent:navigationevent-compose", version.ref = "navigationEvent" }

[plugins]
application = { id = "application" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "androidGradlePlugin" }
androidLint = { id = "com.android.lint", version.ref = "androidGradlePlugin" }
jetbrainsKotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
vanniktechMavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }
